### ISSUE TITLE
Questions about mode train

### ISSUE THREAD

**Issue by xiaoliziwa** [zamanzadeh/CARLA#11]
Hello, esteemed author,
When I run this command, an error occurs：
python carla_pretext.py --config_env configs/env.yml --config_exp configs/pretext/carla_pretext_msl.yml --fname All
![786e79b86ac026bdd423fd944264930](https://github.com/user-attachments/assets/a41470f9-b876-4716-aa35-2b94ccc11357)

**Comment by zamanzadeh** [comment]
Please check updated version
