### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by beomjun02** [zamanzadeh/CARLA#2]
Hello, I am looking forward to using it in my project.

Is GPU usage supported? In the code I don't see GPU usage, and the code is too slow.

Thanks.

**Comment by zamanzadeh** [comment]
Hello! GPU usage isn't supported in the current code. However, we're open to contributions, so feel free to collaborate on adding GPU support to improve performance. Let us know how you'd like to contribute!

Thanks!
