### ISSUE TITLE
about the parameter 

### ISSUE THREAD

**Issue by Wangyangfen** [zamanzadeh/CARLA#7]
Dear Author, Could you kindly share the parameter settings for SMD? Thank you very much!

**Comment by zamanzadeh** [comment]
Hello!
The parameters used in the experiments with the SMD dataset are consistent with those detailed in the article. If you need specific details about any parameter or have any other questions, feel free to ask!

**Comment by 11baqijiangjiang** [comment]
> 尊敬的作者，您能分享一下SMD的参数设置吗？谢谢！

大佬 你好请问您smd复现成功了吗
