### ISSUE TITLE
MSL overall dataset running error

### ISSUE THREAD

**Issue by Wangyangfen** [zamanzadeh/CARLA#9]
Hello, esteemed author, 
    Firstly, I executed the command correctly ：

> python carla_pretext.py --config_env configs/env.yml --config_exp configs/pretext/carla_pretext_msl.yml --fname All

but When I run this command, an error occurs：

> python carla_classification.py --config_env configs/env.yml --config_exp configs/classification/carla_classification_msl.yml --fname All

Traceback (most recent call last):
  File "D:\wyf\code\code11\CARLA-main\CARLA-main\carla_classification.py", line 217, in <module>
    main()
  File "D:\wyf\code\code11\CARLA-main\CARLA-main\carla_classification.py", line 52, in main
    base_dataset = get_train_dataset(p, train_transformations, sanomaly,
  File "D:\wyf\code\code11\CARLA-main\CARLA-main\utils\common_config.py", line 153, in get_train_dataset
    dataset = NeighborsDataset(dataset, None, nindices, findices, p)
  File "D:\wyf\code\code11\CARLA-main\CARLA-main\data\custom_dataset.py", line 105, in __init__
    self.NNeighbor = all_data
IndexError: index 26031 is out of bounds for axis 0 with size 1365

I output two results when printing the results：

> NN_index: [ 26031 102004  70614 ...  95806  98002  98088], all_data.shape: torch.Size([105834, 200, 55])

> NN_index: [ 26031 102004  70614 ...  69154  27493  27753], all_data.shape: (1365, 200, 55)

Can it be solved by skipping the result of the first index

Looking forward to your reply

**Comment by zamanzadeh** [comment]
Hello,

Thanks for your message and the detailed report. The issue you encountered is due to indices exceeding the dataset size, which has been fixed in the latest update of the CARLA model. Please update your code to the latest version where this issue has been addressed. If the problem continues after updating, verify that the dataset loading and preprocessing are configured correctly.

Let me know if the update resolves the issue or if you need further assistance.

**Comment by 11baqijiangjiang** [comment]
> 尊敬的作者您好，首先，我正确执行了命令：
> 
> > python carla_pretext.py --config_env configs/env.yml --config_exp configs/pretext/carla_pretext_msl.yml --fname 全部
> 
> 但是当我运行这个命令时，发生错误：
> 
> > python carla_classification.py --config_env configs/env.yml --config_exp configs/classification/carla_classification_msl.yml --fname 全部
> 
> 回溯（最近一次调用最后）：文件“D：\wyf\code\code11\CARLA-main\CARLA-main\carla_classification.py”，第 217 行，在 main（） 文件“D：\wyf\code\code11\CARLA-main\CARLA-main\carla_classification.py”，第 52 行，在主base_dataset = get_train_dataset（p， train_transformations， sanomaly，文件“D：\wyf\code\code11\CARLA-main\CARLA-main\utils\common_config.py”，第 153 行，在 get_train_dataset 中dataset = NeighborsDataset（dataset， None， nindices， findices， p） 文件“D：\wyf\code\code11\CARLA-main\CARLA-main\data\custom_dataset.py”，第 105 行，在 **init** self 中。NNeighbor = all_data IndexError： index 26031 is out of bounds for axis 0 with size 1365
> 
> 打印结果时输出两个结果：
> 
> > NN_index： [ 26031 102004 70614 ...95806 98002 98088]，all_data.形状：手电筒。尺寸（[105834， 200， 55]）
> 
> > NN_index： [ 26031 102004 70614 ...69154 27493 27753]，all_data.形状：（1365， 200， 55）
> 
> 跳过第一个索引的结果可以解决吗
> 
> 期待您的回复
Hello, esteemed friend,
When running the SMD dataset, the best_pre metric is only 0.27, which is lower than the precision metric of 0.42 in the paper. The b_f1 score is 0.37, also lower than the F1 score of 0.511 in the paper. I don't know where the problem lies.
